# Explotary Data Analysis

In [1]:
# Load dataset and view basic structure

import pandas as pd
import numpy as np

df=pd.read_csv("best-buy-products.csv")
df = df[["sku","name", "customerReviewAverage", "customerReviewCount", "customerTopRated", "manufacturer", "class", "condition", "modelNumber",  "salePrice"]]

# Display the first 5 rows for a quick preview
df.head()

,sku,name,customerReviewAverage,customerReviewCount,customerTopRated,manufacturer,class,condition,modelNumber,salePrice
0,6636904,"Lenovo - T14 G2 14"" Refurbished Laptop - Intel...",3.0,1.0,False,Lenovo,SO LAPTOPS,Refurbished,T14 G2,677.99
1,6636905,"HP - EliteBook 840 G7 14"" Refurbished Laptop -...",NaN,NaN,NaN,HP,SO LAPTOPS,Refurbished,840 G7,574.99
2,6636906,"HP - EliteBook 850 G7 15.6"" Refurbished Laptop...",NaN,NaN,NaN,HP,SO LAPTOPS,Refurbished,850 G7,721.18
3,6636931,"HP - OmniBook X - Copilot+ PC - 17.3"" Full HD ...",4.8,51.0,True,HP,BLUE LABEL,New,C33WSUA#ABA,1599.99
4,6637409,"HP - 15.6"" Laptop - Intel Core i3 - 8GB Memory...",4.7,196.0,True,HP,BURST,New,C0CM1UA#ABA,219.99

## Check structure and dimensions

In [22]:
#shape

df.shape

(846, 10)

In [23]:
# Check structure
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 846 entries, 0 to 1223
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   sku                    846 non-null    int64
 1   name                   846 non-null    object
 2   customerReviewAverage  846 non-null    float64
 3   customerReviewCount    846 non-null    float64
 4   customerTopRated       846 non-null    object
 5   manufacturer           846 non-null    object
 6   class                  846 non-null    object
 7   condition              846 non-null    object
 8   modelNumber            846 non-null    object
 9   salePrice              846 non-null    float64
dtypes: float64(3), int64(1), object(6)
memory usage: 72.7+ KB

In [4]:
#remove rows that are empty
df = df.dropna()

In [5]:
# Print the number of rows and columns
print(f"The number of rows= {df.shape[0]}")
print(f"The number of columns= {df.shape[1]}")

The number of rows= 846
The number of columns= 10

## Columns and Data Types

In [6]:
#display the columns
df.columns

Index(['sku', 'name', 'customerReviewAverage', 'customerReviewCount',
       'customerTopRated', 'manufacturer', 'class', 'condition', 'modelNumber',
       'salePrice'],
      dtype='object')

In [7]:
df.columns.to_list()

['sku',
 'name',
 'customerReviewAverage',
 'customerReviewCount',
 'customerTopRated',
 'manufacturer',
 'class',
 'condition',
 'modelNumber',
 'salePrice']

In [8]:
# Data Types
df.dtypes

sku                        int64
name                      object
customerReviewAverage    float64
customerReviewCount      float64
customerTopRated          object
manufacturer              object
class                     object
condition                 object
modelNumber               object
salePrice                float64
dtype: object

## Using iloc and loc

- .iloc is position-based indexing, while .loc uses label-based indexing.

In [9]:
#Using iloc list the values for row 50,100 and 150

df.iloc[[50,100,150]]

,sku,name,customerReviewAverage,customerReviewCount,customerTopRated,manufacturer,class,condition,modelNumber,salePrice
163,6636736,"HP - 21.5"" All-in-One - Intel N100 - 8GB Memor...",5.0,2.0,False,HP,DESK TOP COMPUTERS,New,22-DG0034,319.99
240,6602763,Apple - MacBook Air 13-inch Laptop - Apple M2 ...,4.9,2474.0,True,Apple,APPLE LAPTOP,New,MC7X4LL/A,799.00
307,6584565,"HP - EliteBook 850 G6 15.6"" Refurbished Laptop...",5.0,2.0,False,HP,SO LAPTOPS,Refurbished,850 G6,514.77

## Descriptive Statistics

In [10]:


# Summary statistics for numeric columns
df.describe()

df.describe(percentiles=[.1, .25, .5, .75, .9])

                sku  customerReviewAverage  customerReviewCount    salePrice
count  8.460000e+02             846.000000           846.000000   846.000000
mean   6.560952e+06               4.300118           245.148936  1001.614173
std    1.141535e+05               0.815813           816.336670   707.467158
min    4.833200e+06               1.000000             1.000000    49.990000
10%    6.489710e+06               3.350000             1.000000   339.990000
25%    6.534623e+06               4.100000             4.000000   499.990000
50%    6.573962e+06               4.500000            31.000000   799.990000
75%    6.611777e+06               4.800000           165.000000  1299.990000
90%    6.622781e+06               5.000000           521.500000  1884.990000
max    7.642148e+06               5.000000         13065.000000  4599.990000

In [11]:
# Summary statistics for categorical columns

df.describe(include='object')

,name,customerTopRated,manufacturer,class,condition,modelNumber
count,846,846,846,846,846,846
unique,802,2,14,12,3,811
top,Apple - Geek Squad Certified Refurbished MacBo...,False,Apple,APPLE LAPTOP,New,GSRF MYDC2LL/A
freq,6,553,411,306,495,4

In [12]:
# Univariate Analysis — Numerical
print('Review count Summary:\n ', df['customerReviewCount'].describe())
print('\nReview avg Score Summary:\n ', df['customerReviewAverage'].describe())

# Univariate Analysis — Categorical
print('\nManufacturer Summary:\n ', df['manufacturer'].describe())
print('\nclass Summary:\n ', df['class'].describe())
print('\nModel number Summary:\n ', df['modelNumber'].describe())
print('\ncondition Summary:\n ', df['condition'].describe())

print('\nManufacturer num:\n ', df['manufacturer'].value_counts())
print('\nclass num:\n ', df['class'].value_counts())

Review count Summary:
  count      846.000000
mean       245.148936
std        816.336670
min          1.000000
25%          4.000000
50%         31.000000
75%        165.000000
max      13065.000000
Name: customerReviewCount, dtype: float64

Review avg Score Summary:
  count    846.000000
mean       4.300118
std        0.815813
min        1.000000
25%        4.100000
50%        4.500000
75%        4.800000
max        5.000000
Name: customerReviewAverage, dtype: float64

Manufacturer Summary:
  count       846
unique       14
top       Apple
freq        411
Name: manufacturer, dtype: object

class Summary:
  count              846
unique              12
top       APPLE LAPTOP
freq               306
Name: class, dtype: object

Model number Summary:
  count                846
unique               811
top       GSRF MYDC2LL/A
freq                   4
Name: modelNumber, dtype: object

condition Summary:
  count     846
unique      3
top       New
freq      495
Name: condition, dtype: object

Manufacturer num:
  manufacturer
Apple        411
HP           131
Lenovo        84
Dell          75
ASUS          73
Samsung       24
Acer          16
MSI           13
LG             7
GIGABYTE       6
Google         2
Microsoft      2
HP OMEN        1
Thomson        1
Name: count, dtype: int64

class num:
  class
APPLE LAPTOP            306
SO LAPTOPS              206
BLUE LABEL              117
DESK TOP COMPUTERS       96
BURST                    47
CHROME                   32
APPLE DESKTOPS           32
VZW IPHONE HDWARE         3
SPRINT IPHONE HDWARE      2
VERIZON HARDWARE          2
SURFACE LAPTOP            2
AT&T IPHONE HDWARE        1
Name: count, dtype: int64

## Data Cleaning Essentials

In [13]:

# Missing values summary

df.isnull().sum()

sku                      0
name                     0
customerReviewAverage    0
customerReviewCount      0
customerTopRated         0
manufacturer             0
class                    0
condition                0
modelNumber              0
salePrice                0
dtype: int64

In [14]:
# Drop duplicates if any

df.drop_duplicates(inplace=True)

In [15]:
df.isnull().sum()

sku                      0
name                     0
customerReviewAverage    0
customerReviewCount      0
customerTopRated         0
manufacturer             0
class                    0
condition                0
modelNumber              0
salePrice                0
dtype: int64

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 846 entries, 0 to 1223
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   sku                    846 non-null    int64
 1   name                   846 non-null    object
 2   customerReviewAverage  846 non-null    float64
 3   customerReviewCount    846 non-null    float64
 4   customerTopRated       846 non-null    object
 5   manufacturer           846 non-null    object
 6   class                  846 non-null    object
 7   condition              846 non-null    object
 8   modelNumber            846 non-null    object
 9   salePrice              846 non-null    float64
dtypes: float64(3), int64(1), object(6)
memory usage: 72.7+ KB

## Summary Statistics Review

In [17]:

# Numerical summaries
print("Mean Review Count:", df['customerReviewCount'].mean())
print("Std of Review Count:",df['customerReviewCount'].std() )
print("Min & Max Review Count:",df['customerReviewCount'].min(), df['customerReviewCount'].max() )

print("Mean Review Rating:", df['customerReviewAverage'].mean())
print("Std of Review Rating:",df['customerReviewAverage'].std() )
print("Min & Max Review Rating:",df['customerReviewAverage'].min(), df['customerReviewAverage'].max() )

# Categorical summaries
print('\nManufacturer counts:\n ', df['manufacturer'].value_counts())
print('\nClass Counts:\n ', df['class'].value_counts())

Mean Review Count: 245.14893617021278
Std of Review Count: 816.3366700429763
Min & Max Review Count: 1.0 13065.0
Mean Review Rating: 4.300118203309692
Std of Review Rating: 0.8158126512070228
Min & Max Review Rating: 1.0 5.0

Manufacturer counts:
  manufacturer
Apple        411
HP           131
Lenovo        84
Dell          75
ASUS          73
Samsung       24
Acer          16
MSI           13
LG             7
GIGABYTE       6
Google         2
Microsoft      2
HP OMEN        1
Thomson        1
Name: count, dtype: int64

Class Counts:
  class
APPLE LAPTOP            306
SO LAPTOPS              206
BLUE LABEL              117
DESK TOP COMPUTERS       96
BURST                    47
CHROME                   32
APPLE DESKTOPS           32
VZW IPHONE HDWARE         3
SPRINT IPHONE HDWARE      2
VERIZON HARDWARE          2
SURFACE LAPTOP            2
AT&T IPHONE HDWARE        1
Name: count, dtype: int64

In [19]:
#Another way of showing std and var
std = df[['Fare']]\
        .apply(['var', 'std'])
std

KeyError: "None of [Index(['Fare'], dtype='object')] are in the [columns]"

In [20]:
#unique value counts and mode detection
print("\nUnique value counts per column:")
print(df.nunique())

Unique value counts per column:
sku                      846
name                     802
customerReviewAverage     30
customerReviewCount      254
customerTopRated           2
manufacturer              14
class                     12
condition                  3
modelNumber              811
salePrice                286
dtype: int64

## Exploring Relationships

In [21]:
# Group-based summaries


print("Mean Fare by Passenger Class:")
print(df.groupby('Pclass')['Fare'].mean())

print("\nSurvival rate by Sex:")
print(df.groupby('Sex')['Survived'].mean())

print("\nSurvival rate by Class and Sex:")
print(df.groupby(['Pclass','Sex'])['Survived'].mean())

# Correlation matrix

df.corr(numeric_only=True)

Mean Fare by Passenger Class:

KeyError: 'Pclass'

In [ ]:
# Bivariate Analysis — Numeric vs Numeric
print("Correlation between Age and Fare:\n",df[['Age', 'Fare']].corr() )

# Bivariate Analysis — Numeric vs Categorical
print("\nAverage Fare by Survival Status:\n", df[['Fare', 'Survived']].corr())

# # Bivariate Analysis — Categorical vs Categorical
print("\nSurvival counts by Embarked port:\n",pd.crosstab(df['Survived'], df['Embarked']))

Correlation between Age and Fare:
            Age      Fare
Age   1.000000  0.096688
Fare  0.096688  1.000000

Average Fare by Survival Status:
               Fare  Survived
Fare      1.000000  0.257307
Survived  0.257307  1.000000

Survival counts by Embarked port:
 Embarked   C   Q    S
Survived
0         75  47  427
1         93  30  219

## Outlier Detection (Without Plots)

In [ ]:

# Using IQR method
Q1 = df['Fare'].quantile(0.25)
Q3 = df['Fare'].quantile(0.75)
IQR = Q3 - Q1

outliers =df[(df['Fare']<(Q1-1.5*IQR))| (df['Fare']>(Q3+1.5*IQR))]
print("Number of outliers in Fare:", outliers.shape[0])

# Using Z-Score method
from scipy import stats
z = stats.zscore(df['Fare'])
print("Potential outliers (Z > 3):", df[abs(z) > 3].shape[0])

Number of outliers in Fare: 116
Potential outliers (Z > 3): 20

In [ ]:
round(np.mean(df['Fare']))

- Univariate

Understand individual variables	.describe(), .value_counts(), .mean(), .std()

- Bivariate

Explore relationships between two variables	groupby(), crosstab(), .corr()