# Explotary Data Analysis

In [8]:
# Load dataset and view basic structure

import pandas as pd
import numpy as np

df=pd.read_csv("best-buy-products-bestseller-col.csv")
df = df[["sku","name", "customerReviewAverage", "customerReviewCount", "customerTopRated", "manufacturer", "class", "condition", "modelNumber",  "salePrice", "bestseller", "rank"]]

df["rank"] = df["rank"].fillna(0)

## Check structure and dimensions

In [3]:
#shape

df.shape

(1224, 12)

In [10]:
# Check structure
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 846 entries, 0 to 1223
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   sku                    846 non-null    int64
 1   name                   846 non-null    object
 2   customerReviewAverage  846 non-null    float64
 3   customerReviewCount    846 non-null    float64
 4   customerTopRated       846 non-null    object
 5   manufacturer           846 non-null    object
 6   class                  846 non-null    object
 7   condition              846 non-null    object
 8   modelNumber            846 non-null    object
 9   salePrice              846 non-null    float64
 10  bestseller             846 non-null    bool
 11  rank                   846 non-null    float64
dtypes: bool(1), float64(4), int64(1), object(6)
memory usage: 80.1+ KB

In [9]:
#remove rows that are empty
df = df.dropna()

In [42]:
# Print the number of rows and columns
print(f"The number of rows= {df.shape[0]}")
print(f"The number of columns= {df.shape[1]}")

The number of rows= 846
The number of columns= 10

## Columns and Data Types

In [27]:
#display the columns
df.columns

Index(['sku', 'name', 'customerReviewAverage', 'customerReviewCount',
       'customerTopRated', 'manufacturer', 'class', 'condition', 'modelNumber',
       'salePrice'],
      dtype='object')

In [28]:
df.columns.to_list()

['sku',
 'name',
 'customerReviewAverage',
 'customerReviewCount',
 'customerTopRated',
 'manufacturer',
 'class',
 'condition',
 'modelNumber',
 'salePrice']

In [29]:
# Data Types
df.dtypes

sku                        int64
name                      object
customerReviewAverage    float64
customerReviewCount      float64
customerTopRated          object
manufacturer              object
class                     object
condition                 object
modelNumber               object
salePrice                float64
dtype: object

## Using iloc and loc

- .iloc is position-based indexing, while .loc uses label-based indexing.

In [30]:
#Using iloc list the values for row 50,100 and 150

df.iloc[[50,100,150]]

,sku,name,customerReviewAverage,customerReviewCount,customerTopRated,manufacturer,class,condition,modelNumber,salePrice
151,6602763,Apple - MacBook Air 13-inch Laptop - Apple M2 ...,4.9,2474.0,True,Apple,phone,New,MC7X4LL/A,799.00
218,6584565,"HP - EliteBook 850 G6 15.6"" Refurbished Laptop...",5.0,2.0,False,HP,phone,Refurbished,850 G6,514.77
281,6598740,Apple - Geek Squad Certified Refurbished MacBo...,4.5,15.0,True,Apple,phone,Refurbished,TI-GSRF MRXN3LL/A,599.99

## Descriptive Statistics

In [31]:


# Summary statistics for numeric columns
df.describe()

df.describe(percentiles=[.1, .25, .5, .75, .9])

                sku  customerReviewAverage  customerReviewCount    salePrice
count  1.548000e+03            1548.000000          1548.000000  1548.000000
mean   6.562660e+06               4.286628           257.746770  1006.157248
std    9.313594e+04               0.817968           848.869938   718.088452
min    4.833200e+06               1.000000             1.000000    49.990000
10%    6.489731e+06               3.300000             1.000000   339.990000
25%    6.534624e+06               4.100000             4.000000   499.990000
50%    6.573486e+06               4.500000            31.500000   799.990000
75%    6.610629e+06               4.800000           169.000000  1299.990000
90%    6.622617e+06               5.000000           554.000000  1899.990000
max    7.642148e+06               5.000000         13065.000000  4599.990000

In [32]:
# Summary statistics for categorical columns

df.describe(include='object')

,name,customerTopRated,manufacturer,class,condition,modelNumber
count,1548,1548,1548,1548,1548,1548
unique,794,2,13,3,3,803
top,Apple - Geek Squad Certified Refurbished MacBo...,False,Apple,phone,New,GSRF MYDC2LL/A
freq,12,1023,763,710,886,8

In [33]:
# Univariate Analysis — Numerical
print('Review count Summary:\n ', df['customerReviewCount'].describe())
print('\nReview avg Score Summary:\n ', df['customerReviewAverage'].describe())
print('\n Sale Price Summary:\n ', df['salePrice'].describe())



# Univariate Analysis — Categorical
print('\nManufacturer Summary:\n ', df['manufacturer'].describe())
print('\nclass Summary:\n ', df['class'].describe())
print('\nModel number Summary:\n ', df['modelNumber'].describe())
print('\ncondition Summary:\n ', df['condition'].describe())

print('\nManufacturer num:\n ', df['manufacturer'].value_counts())
print('\nclass num:\n ', df['class'].value_counts())

Review count Summary:
  count     1548.000000
mean       257.746770
std        848.869938
min          1.000000
25%          4.000000
50%         31.500000
75%        169.000000
max      13065.000000
Name: customerReviewCount, dtype: float64

Review avg Score Summary:
  count    1548.000000
mean        4.286628
std         0.817968
min         1.000000
25%         4.100000
50%         4.500000
75%         4.800000
max         5.000000
Name: customerReviewAverage, dtype: float64

 Sale Price Summary:
  count    1548.000000
mean     1006.157248
std       718.088452
min        49.990000
25%       499.990000
50%       799.990000
75%      1299.990000
max      4599.990000
Name: salePrice, dtype: float64

Manufacturer Summary:
  count      1548
unique       13
top       Apple
freq        763
Name: manufacturer, dtype: object

class Summary:
  count      1548
unique        3
top       phone
freq        710
Name: class, dtype: object

Model number Summary:
  count               1548
unique               803
top       GSRF MYDC2LL/A
freq                   8
Name: modelNumber, dtype: object

condition Summary:
  count     1548
unique       3
top        New
freq       886
Name: condition, dtype: object

Manufacturer num:
  manufacturer
Apple        763
HP           227
Lenovo       153
ASUS         142
Dell         130
Samsung       48
Acer          30
MSI           21
LG            14
GIGABYTE      12
Microsoft      4
HP OMEN        2
Thomson        2
Name: count, dtype: int64

class num:
  class
phone      710
laptop     710
desktop    128
Name: count, dtype: int64

## Data Cleaning Essentials

In [43]:

# Missing values summary

df.isnull().sum()

sku                      0
name                     0
customerReviewAverage    0
customerReviewCount      0
customerTopRated         0
manufacturer             0
class                    0
condition                0
modelNumber              0
salePrice                0
dtype: int64

In [44]:
# Drop duplicates if any

df.drop_duplicates(inplace=True)

In [45]:
df.isnull().sum()

sku                      0
name                     0
customerReviewAverage    0
customerReviewCount      0
customerTopRated         0
manufacturer             0
class                    0
condition                0
modelNumber              0
salePrice                0
dtype: int64

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 846 entries, 0 to 1223
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   sku                    846 non-null    int64
 1   name                   846 non-null    object
 2   customerReviewAverage  846 non-null    float64
 3   customerReviewCount    846 non-null    float64
 4   customerTopRated       846 non-null    object
 5   manufacturer           846 non-null    object
 6   class                  846 non-null    object
 7   condition              846 non-null    object
 8   modelNumber            846 non-null    object
 9   salePrice              846 non-null    float64
dtypes: float64(3), int64(1), object(6)
memory usage: 72.7+ KB

## Summary Statistics Review

In [47]:

# Numerical summaries
print("Review Count")
print("Mean Review Count:", df['customerReviewCount'].mean())
print("Std of Review Count:",df['customerReviewCount'].std() )
print("Min & Max Review Count:",df['customerReviewCount'].min(), df['customerReviewCount'].max() )

print("\nReview Rating")
print("Mean Review Rating:", df['customerReviewAverage'].mean())
print("Std of Review Rating:",df['customerReviewAverage'].std() )
print("Min & Max Review Rating:",df['customerReviewAverage'].min(), df['customerReviewAverage'].max() )

print("\nSale Price")

print("Mean Sale Price:", df['salePrice'].mean())
print("Std of Sale Price:",df['salePrice'].std() )
print("Min & Max Sale Price:",df['salePrice'].min(), df['salePrice'].max() )

# Categorical summaries
print('\nManufacturer counts:\n ', df['manufacturer'].value_counts())
print('\nClass Counts:\n ', df['class'].value_counts())

Review Count
Mean Review Count: 245.14893617021278
Std of Review Count: 816.3366700429764
Min & Max Review Count: 1.0 13065.0

Review Rating
Mean Review Rating: 4.300118203309693
Std of Review Rating: 0.8158126512070224
Min & Max Review Rating: 1.0 5.0

Sale Price
Mean Sale Price: 1001.6141725768321
Std of Sale Price: 707.4671576098312
Min & Max Sale Price: 49.99 4599.99

Manufacturer counts:
  manufacturer
Apple        411
HP           131
Lenovo        84
Dell          75
ASUS          73
Samsung       24
Acer          16
MSI           13
LG             7
GIGABYTE       6
Google         2
Microsoft      2
HP OMEN        1
Thomson        1
Name: count, dtype: int64

Class Counts:
  class
laptop     710
desktop    128
phone        8
Name: count, dtype: int64

In [ ]:
#Another way of showing std and var
std = df[['Fare']]\
        .apply(['var', 'std'])
std

            Fare
var  2469.436846
std    49.693429

In [19]:
#unique value counts and mode detection
print("\nUnique value counts per column:")
print(df.nunique())

Unique value counts per column:
sku                      846
name                     802
customerReviewAverage     30
customerReviewCount      254
customerTopRated           2
manufacturer              14
class                     12
condition                  3
modelNumber              811
salePrice                286
dtype: int64

## Exploring Relationships

In [14]:
# Group-based summaries

print("Mean Rating by Class:")
print(df.groupby('class')['customerReviewAverage'].mean())

print("\nMean Rating by Manufacturer:")
print(df.groupby('manufacturer')['customerReviewAverage'].mean())

print("\nMean Review Count by Class:")
print(df.groupby('class')['customerReviewCount'].mean())

print("\nMean Review Count by Manufacturer:")
print(df.groupby('manufacturer')['customerReviewCount'].mean())

print("\nMean Sale Price by Class:")
print(df.groupby('class')['salePrice'].mean())

print("\nMean Sale Price by Manufacturer:")
print(df.groupby('manufacturer')['salePrice'].mean())

print("\nMean Rating by Bestseller:")
print(df.groupby(['class','bestseller'])['customerReviewAverage'].mean())

print("\nMean Sale Price by bestseller:")
print(df.groupby(['class','bestseller'])['salePrice'].mean())





# Correlation matrix

df.corr(numeric_only=True)

Mean Rating by Class:
class
desktop    4.555469
laptop     4.262394
phone      3.562500
Name: customerReviewAverage, dtype: float64

Mean Rating by Manufacturer:
manufacturer
ASUS         4.430137
Acer         4.218750
Apple        4.200243
Dell         4.256000
GIGABYTE     3.133333
Google       5.000000
HP           4.482443
HP OMEN      4.000000
LG           4.800000
Lenovo       4.576190
MSI          3.800000
Microsoft    3.650000
Samsung      4.325000
Thomson      3.000000
Name: customerReviewAverage, dtype: float64

Mean Review Count by Class:
class
desktop    123.046875
laptop     269.888732
phone        3.125000
Name: customerReviewCount, dtype: float64

Mean Review Count by Manufacturer:
manufacturer
ASUS          81.205479
Acer         145.500000
Apple        319.866180
Dell         111.720000
GIGABYTE       2.833333
Google         1.000000
HP           283.832061
HP OMEN        4.000000
LG            23.571429
Lenovo       226.261905
MSI            2.538462
Microsoft      4.000000
Samsung      119.875000
Thomson        2.000000
Name: customerReviewCount, dtype: float64

Mean Sale Price by Class:
class
desktop     994.414375
laptop     1007.215761
phone       619.670000
Name: salePrice, dtype: float64

Mean Sale Price by Manufacturer:
manufacturer
ASUS         1322.360411
Acer          723.681250
Apple         989.277908
Dell         1046.704533
GIGABYTE     3125.656667
Google       1099.990000
HP            736.959008
HP OMEN      1769.990000
LG           1807.132857
Lenovo        932.336310
MSI          1337.451538
Microsoft    1199.990000
Samsung       997.490000
Thomson       199.990000
Name: salePrice, dtype: float64

Mean Rating by Bestseller:
class    bestseller
desktop  False         4.539831
         True          4.740000
laptop   False         4.256348
         True          4.733333
phone    False         3.020000
         True          4.466667
Name: customerReviewAverage, dtype: float64

Mean Sale Price by bestseller:
class    bestseller
desktop  False         1026.840000
         True           611.792000
laptop   False         1012.919044
         True           562.993333
phone    False          484.282000
         True           845.316667
Name: salePrice, dtype: float64

,sku,customerReviewAverage,customerReviewCount,salePrice,bestseller,rank
sku,1.000000,0.065165,-0.022200,0.140592,0.064065,0.057357
customerReviewAverage,0.065165,1.000000,0.153745,0.014183,0.080139,0.081551
customerReviewCount,-0.022200,0.153745,1.000000,-0.055356,0.053354,0.019862
salePrice,0.140592,0.014183,-0.055356,1.000000,-0.087342,-0.072502
bestseller,0.064065,0.080139,0.053354,-0.087342,1.000000,0.875416
rank,0.057357,0.081551,0.019862,-0.072502,0.875416,1.000000

In [12]:
# Bivariate Analysis — Numeric vs Numeric
print("Correlation between rating and bestseller:\n",df[['customerReviewAverage', 'bestseller']].corr() )

# # Bivariate Analysis — Numeric vs Categorical
# print("\nAverage Fare by Survival Status:\n", df[['Fare', 'Survived']].corr())

# # # Bivariate Analysis — Categorical vs Categorical
# print("\nSurvival counts by Embarked port:\n",pd.crosstab(df['Survived'], df['Embarked']))

Correlation between rating and bestseller:
                        customerReviewAverage  bestseller
customerReviewAverage               1.000000    0.080139
bestseller                          0.080139    1.000000

- Univariate

Understand individual variables	.describe(), .value_counts(), .mean(), .std()

- Bivariate

Explore relationships between two variables	groupby(), crosstab(), .corr()