# Explotary Data Analysis Best Buy

In [1]:
# Load dataset and view basic structure

import pandas as pd
import numpy as np

pd.set_option("display.max_rows", None)
pd.set_option("display.max_seq_items", None)

df=pd.read_csv("filtered_products_bestbuy.csv")

## Data Inspection and Cleaning

This section examines the structure and quality of the dataset to ensure it is prepared for analysis. The number of rows and columns, data types and missing values are inspected. These checks help identify incomplete, duplicated, or inconsistent records. Rows with missing values are removed, duplicate entries are dropped, and products with zero reviews are filtered out, as they do not contribute meaningful insight. A final structural check confirms that the dataset is complete, consistent, and ready for exploratory analysis

In [2]:
#shape

df.shape

(1224, 12)

In [3]:
# Check structure
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1224 entries, 0 to 1223
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   sku                    1224 non-null   int64
 1   name                   1224 non-null   object
 2   customerReviewAverage  846 non-null    float64
 3   customerReviewCount    846 non-null    float64
 4   customerTopRated       846 non-null    object
 5   manufacturer           1223 non-null   object
 6   class                  1224 non-null   object
 7   condition              1224 non-null   object
 8   modelNumber            1223 non-null   object
 9   salePrice              1224 non-null   float64
 10  bestseller             1224 non-null   bool
 11  rank                   1224 non-null   float64
dtypes: bool(1), float64(4), int64(1), object(6)
memory usage: 106.5+ KB

In [4]:

# Missing values summary
df.isnull().sum()

sku                        0
name                       0
customerReviewAverage    378
customerReviewCount      378
customerTopRated         378
manufacturer               1
class                      0
condition                  0
modelNumber                1
salePrice                  0
bestseller                 0
rank                       0
dtype: int64

In [5]:
# Print the number of rows and columns
print(f"The number of rows= {df.shape[0]}")
print(f"The number of columns= {df.shape[1]}")

The number of rows= 1224
The number of columns= 12

In [6]:
#display the columns
df.columns

Index(['sku', 'name', 'customerReviewAverage', 'customerReviewCount',
       'customerTopRated', 'manufacturer', 'class', 'condition', 'modelNumber',
       'salePrice', 'bestseller', 'rank'],
      dtype='object')

In [7]:
df.columns.to_list()

['sku',
 'name',
 'customerReviewAverage',
 'customerReviewCount',
 'customerTopRated',
 'manufacturer',
 'class',
 'condition',
 'modelNumber',
 'salePrice',
 'bestseller',
 'rank']

In [8]:
# Data Types
df.dtypes

sku                        int64
name                      object
customerReviewAverage    float64
customerReviewCount      float64
customerTopRated          object
manufacturer              object
class                     object
condition                 object
modelNumber               object
salePrice                float64
bestseller                  bool
rank                     float64
dtype: object

In [9]:
#remove rows that are empty
df = df.dropna()

In [10]:
# Drop duplicates if any
df.drop_duplicates(inplace=True)

In [11]:

# Missing values summary

df.isnull().sum()

sku                      0
name                     0
customerReviewAverage    0
customerReviewCount      0
customerTopRated         0
manufacturer             0
class                    0
condition                0
modelNumber              0
salePrice                0
bestseller               0
rank                     0
dtype: int64

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 846 entries, 0 to 1223
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   sku                    846 non-null    int64
 1   name                   846 non-null    object
 2   customerReviewAverage  846 non-null    float64
 3   customerReviewCount    846 non-null    float64
 4   customerTopRated       846 non-null    object
 5   manufacturer           846 non-null    object
 6   class                  846 non-null    object
 7   condition              846 non-null    object
 8   modelNumber            846 non-null    object
 9   salePrice              846 non-null    float64
 10  bestseller             846 non-null    bool
 11  rank                   846 non-null    float64
dtypes: bool(1), float64(4), int64(1), object(6)
memory usage: 80.1+ KB

## Descriptive Statistics

This section provides an initial exploration of the dataset to understand patterns, distributions, and key characteristics. Numerical features are summarized using measures such as mean, median, quartiles, and standard deviation, while categorical variables are described through frequency counts. These outputs reveal how ratings, review counts, and prices are distributed, and how product categories and manufacturers are represented. The results help identify early trends in customer behavior, product performance, and dataset composition.

In [13]:


# Summary statistics for numeric columns
df.describe()

df.describe(percentiles=[.1, .25, .5, .75, .9])

,sku,customerReviewAverage,customerReviewCount,salePrice,rank
count,8.460000e+02,846.000000,846.000000,846.000000,846.000000
mean,6.560952e+06,4.300118,245.148936,1001.614173,0.138298
std,1.141535e+05,0.815813,816.336670,707.467158,0.967409
min,4.833200e+06,1.000000,1.000000,49.990000,0.000000
10%,6.489710e+06,3.350000,1.000000,339.990000,0.000000
25%,6.534623e+06,4.100000,4.000000,499.990000,0.000000
50%,6.573962e+06,4.500000,31.000000,799.990000,0.000000
75%,6.611777e+06,4.800000,165.000000,1299.990000,0.000000
90%,6.622781e+06,5.000000,521.500000,1884.990000,0.000000
max,7.642148e+06,5.000000,13065.000000,4599.990000,10.000000

In [14]:
# Summary statistics for categorical columns

df.describe(include='object')

,name,customerTopRated,manufacturer,class,condition,modelNumber
count,846,846,846,846,846,846
unique,802,2,14,3,3,811
top,Apple - Geek Squad Certified Refurbished MacBo...,False,Apple,laptop,New,GSRF MYDC2LL/A
freq,6,553,411,710,495,4

In [15]:
# Univariate Analysis — Numerical
print('Review count Summary:\n ', df['customerReviewCount'].describe())
print('\nReview avg Score Summary:\n ', df['customerReviewAverage'].describe())
print('\n Sale Price Summary:\n ', df['salePrice'].describe())
# Univariate Analysis — Categorical
print('\nManufacturer Summary:\n ', df['manufacturer'].describe())
print('\nclass Summary:\n ', df['class'].describe())
print('\nModel number Summary:\n ', df['modelNumber'].describe())
print('\ncondition Summary:\n ', df['condition'].describe())

# Value counts help us understand category frequency distribution.
print('\nManufacturer num:\n ', df['manufacturer'].value_counts())
print('\nclass num:\n ', df['class'].value_counts())

Review count Summary:
  count      846.000000
mean       245.148936
std        816.336670
min          1.000000
25%          4.000000
50%         31.000000
75%        165.000000
max      13065.000000
Name: customerReviewCount, dtype: float64

Review avg Score Summary:
  count    846.000000
mean       4.300118
std        0.815813
min        1.000000
25%        4.100000
50%        4.500000
75%        4.800000
max        5.000000
Name: customerReviewAverage, dtype: float64

 Sale Price Summary:
  count     846.000000
mean     1001.614173
std       707.467158
min        49.990000
25%       499.990000
50%       799.990000
75%      1299.990000
max      4599.990000
Name: salePrice, dtype: float64

Manufacturer Summary:
  count       846
unique       14
top       Apple
freq        411
Name: manufacturer, dtype: object

class Summary:
  count        846
unique         3
top       laptop
freq         710
Name: class, dtype: object

Model number Summary:
  count                846
unique               811
top       GSRF MYDC2LL/A
freq                   4
Name: modelNumber, dtype: object

condition Summary:
  count     846
unique      3
top       New
freq      495
Name: condition, dtype: object

Manufacturer num:
  manufacturer
Apple        411
HP           131
Lenovo        84
Dell          75
ASUS          73
Samsung       24
Acer          16
MSI           13
LG             7
GIGABYTE       6
Google         2
Microsoft      2
HP OMEN        1
Thomson        1
Name: count, dtype: int64

class num:
  class
laptop     710
desktop    128
phone        8
Name: count, dtype: int64

## Detailed Statistical Summaries & Outlier Analysis

This section computes central tendency and variability measures for key numerical variables, including review count, review rating, and sale price. Statistics such as mean, median, mode, variance, and standard deviation describe typical values and the spread of the data. Outlier detection is performed using both the Interquartile Range (IQR) method and z-scores to identify unusually high or low observations. These outliers are important to recognize because they may influence averages or indicate exceptional product cases.

In [16]:

# Numerical summaries
print("Review Count")
print("Mean Review Count:", df['customerReviewCount'].mean())
print("Median Review Count:", df['customerReviewCount'].median())
print("Mode Review Count:", df['customerReviewCount'].mode()[0])
print("Std of Review Count:",df['customerReviewCount'].std() )
print("Variance of Review Count:",df['customerReviewCount'].var() )
print("Min & Max Review Count:",df['customerReviewCount'].min(), df['customerReviewCount'].max() )

# Using IQR (inter quartile range) method
Q1 = df['customerReviewCount'].quantile(.25)
Q3 = df['customerReviewCount'].quantile(.75)
IQR = Q3 - Q1

lower_fence = Q1 - IQR*1.5
upper_fence = Q3 + IQR*1.5
outliers = df[(df['customerReviewCount']<lower_fence)|(df['customerReviewCount']>upper_fence)]
print("Number of outliers Review Count:", outliers.shape[0])

# Using Z-Score method
from scipy import stats
z = stats.zscore(df['customerReviewCount'])
print("Potential outliers (Z > 3):", df[abs(z) > 3].shape[0])

print("\nReview Rating")
print("Mean Review Rating:", df['customerReviewAverage'].mean())
print("Median Review Rating:", df['customerReviewAverage'].median())
print("Mode Review Rating:", df['customerReviewAverage'].mode()[0])
print("Std of Review Rating:",df['customerReviewAverage'].std() )
print("Variance of Review Rating:",df['customerReviewAverage'].var() )
print("Min & Max Review Rating:",df['customerReviewAverage'].min(), df['customerReviewAverage'].max() )

# Using IQR (inter quartile range) method
Q1 = df['customerReviewAverage'].quantile(.25)
Q3 = df['customerReviewAverage'].quantile(.75)
IQR = Q3 - Q1

lower_fence = Q1 - IQR*1.5
upper_fence = Q3 + IQR*1.5
outliers = df[(df['customerReviewAverage']<lower_fence)|(df['customerReviewAverage']>upper_fence)]
print("Number of outliers Review Rating:", outliers.shape[0])

# Using Z-Score method
z = stats.zscore(df['customerReviewAverage'])
print("Potential outliers (Z > 3):", df[abs(z) > 3].shape[0])

print("\nSale Price")
print("Mean Sale Price:", df['salePrice'].mean())
print("Median Sale Price:", df['salePrice'].median())
print("Mode Sale Price:", df['salePrice'].mode()[0])
print("Std of Sale Price:",df['salePrice'].std() )
print("Variance of Sale Price:",df['salePrice'].var() )
print("Min & Max Sale Price:",df['salePrice'].min(), df['salePrice'].max() )

# Using IQR (inter quartile range) method
Q1 = df['salePrice'].quantile(.25)
Q3 = df['salePrice'].quantile(.75)
IQR = Q3 - Q1

lower_fence = Q1 - IQR*1.5
upper_fence = Q3 + IQR*1.5
outliers = df[(df['salePrice']<lower_fence)|(df['salePrice']>upper_fence)]
print("Number of outliers Sale Price:", outliers.shape[0])

# Using Z-Score method
z = stats.zscore(df['salePrice'])
print("Potential outliers (Z > 3):", df[abs(z) > 3].shape[0])

Review Count
Mean Review Count: 245.14893617021278
Median Review Count: 31.0
Mode Review Count: 1.0
Std of Review Count: 816.3366700429764
Variance of Review Count: 666405.5588568554
Min & Max Review Count: 1.0 13065.0
Number of outliers Review Count: 113
Potential outliers (Z > 3): 11

Review Rating
Mean Review Rating: 4.300118203309693
Median Review Rating: 4.5
Mode Review Rating: 5.0
Std of Review Rating: 0.8158126512070224
Variance of Review Rating: 0.6655502818694308
Min & Max Review Rating: 1.0 5.0
Number of outliers Review Rating: 74
Potential outliers (Z > 3): 24

Sale Price
Mean Sale Price: 1001.6141725768321
Median Sale Price: 799.99
Mode Sale Price: 899.99
Std of Sale Price: 707.4671576098312
Variance of Sale Price: 500509.7790965338
Min & Max Sale Price: 49.99 4599.99
Number of outliers Sale Price: 36
Potential outliers (Z > 3): 19

## Categorical variable frequency summaries

This section summarizes the frequency of key categorical variables such as manufacturer and product class. Understanding how often each category appears provides insight into dataset balance, representation, and potential sources of bias. These distributions also support later comparisons between groups when analyzing ratings, review activity, and prices.

In [17]:
# Categorical summaries
print('\nManufacturer counts:\n ', df['manufacturer'].value_counts())
print('\nClass Counts:\n ', df['class'].value_counts())

Manufacturer counts:
  manufacturer
Apple        411
HP           131
Lenovo        84
Dell          75
ASUS          73
Samsung       24
Acer          16
MSI           13
LG             7
GIGABYTE       6
Google         2
Microsoft      2
HP OMEN        1
Thomson        1
Name: count, dtype: int64

Class Counts:
  class
laptop     710
desktop    128
phone        8
Name: count, dtype: int64

## Unique Value Counts

This section reports the number of unique values in each column. Unique value counts help determine the variability of different features and identify which fields are useful for grouping or aggregation. For example, columns with many unique values (such as model numbers) behave differently from those with only a few categories (such as class or condition).

In [18]:
#unique value counts and mode detection
print("\nUnique value counts per column:")
print(df.nunique())

Unique value counts per column:
sku                      846
name                     802
customerReviewAverage     30
customerReviewCount      254
customerTopRated           2
manufacturer              14
class                      3
condition                  3
modelNumber              811
salePrice                286
bestseller                 2
rank                      11
dtype: int64

## Exploring Relationships

This section computes grouped summary statistics to compare rating averages, review counts, and sale prices across product classes and manufacturers. Grouped means highlight meaningful differences between product types or brands and reveal trends that help identify which categories tend to perform better in customer ratings, attract more reviews, or fall into different price ranges.

In [19]:
# Group-based summaries

print("Mean Rating by Class:")
print(df.groupby('class')['customerReviewAverage'].mean())

print("\nMean Rating by Manufacturer:")
print(df.groupby('manufacturer')['customerReviewAverage'].mean())

print("\nMean Review Count by Class:")
print(df.groupby('class')['customerReviewCount'].mean())

print("\nMean Review Count by Manufacturer:")
print(df.groupby('manufacturer')['customerReviewCount'].mean())

print("\nMean Sale Price by Class:")
print(df.groupby('class')['salePrice'].mean())

print("\nMean Sale Price by Manufacturer:")
print(df.groupby('manufacturer')['salePrice'].mean())

print("\nMean Rating by Bestseller:")
print(df.groupby(['class','bestseller'])['customerReviewAverage'].mean())

print("\nMean Sale Price by bestseller:")
print(df.groupby(['class','bestseller'])['salePrice'].mean())

Mean Rating by Class:
class
desktop    4.555469
laptop     4.262394
phone      3.562500
Name: customerReviewAverage, dtype: float64

Mean Rating by Manufacturer:
manufacturer
ASUS         4.430137
Acer         4.218750
Apple        4.200243
Dell         4.256000
GIGABYTE     3.133333
Google       5.000000
HP           4.482443
HP OMEN      4.000000
LG           4.800000
Lenovo       4.576190
MSI          3.800000
Microsoft    3.650000
Samsung      4.325000
Thomson      3.000000
Name: customerReviewAverage, dtype: float64

Mean Review Count by Class:
class
desktop    123.046875
laptop     269.888732
phone        3.125000
Name: customerReviewCount, dtype: float64

Mean Review Count by Manufacturer:
manufacturer
ASUS          81.205479
Acer         145.500000
Apple        319.866180
Dell         111.720000
GIGABYTE       2.833333
Google         1.000000
HP           283.832061
HP OMEN        4.000000
LG            23.571429
Lenovo       226.261905
MSI            2.538462
Microsoft      4.000000
Samsung      119.875000
Thomson        2.000000
Name: customerReviewCount, dtype: float64

Mean Sale Price by Class:
class
desktop     994.414375
laptop     1007.215761
phone       619.670000
Name: salePrice, dtype: float64

Mean Sale Price by Manufacturer:
manufacturer
ASUS         1322.360411
Acer          723.681250
Apple         989.277908
Dell         1046.704533
GIGABYTE     3125.656667
Google       1099.990000
HP            736.959008
HP OMEN      1769.990000
LG           1807.132857
Lenovo        932.336310
MSI          1337.451538
Microsoft    1199.990000
Samsung       997.490000
Thomson       199.990000
Name: salePrice, dtype: float64

Mean Rating by Bestseller:
class    bestseller
desktop  False         4.539831
         True          4.740000
laptop   False         4.256348
         True          4.733333
phone    False         3.020000
         True          4.466667
Name: customerReviewAverage, dtype: float64

Mean Sale Price by bestseller:
class    bestseller
desktop  False         1026.840000
         True           611.792000
laptop   False         1012.919044
         True           562.993333
phone    False          484.282000
         True           845.316667
Name: salePrice, dtype: float64

The grouped statistics reveal that products with higher average ratings tend to receive more reviews. For example, desktop and laptop products marked as “bestsellers” have higher ratings (4.74 and 4.73) and substantial review counts compared to lower-rated products. Similarly, top-rated phones, despite being few, show increased review activity relative to lower-rated phones. These patterns suggest that positive customer experiences are associated with higher likelihood of leaving reviews. Differences across manufacturers also reflect this trend, with highly-rated brands such as Google, Lenovo, and LG showing higher average ratings and relatively high review counts where sample sizes allow.

## Correlation Analysis

This section calculates a correlation matrix for the numerical variables to explore relationships within the dataset. Correlation values indicate whether variables move together, such as whether higher review counts are associated with higher ratings or whether price is connected to customer engagement. Identifying these relationships completes the exploratory analysis by showing how numerical features interact.

In [20]:
# Correlation matrix

df.corr(numeric_only=True)

,sku,customerReviewAverage,customerReviewCount,salePrice,bestseller,rank
sku,1.000000,0.065165,-0.022200,0.140592,0.064065,0.057357
customerReviewAverage,0.065165,1.000000,0.153745,0.014183,0.080139,0.081551
customerReviewCount,-0.022200,0.153745,1.000000,-0.055356,0.053354,0.019862
salePrice,0.140592,0.014183,-0.055356,1.000000,-0.087342,-0.072502
bestseller,0.064065,0.080139,0.053354,-0.087342,1.000000,0.875416
rank,0.057357,0.081551,0.019862,-0.072502,0.875416,1.000000

In [21]:
# Bivariate Analysis — Numeric vs Numeric
print("Correlation between rating and bestseller:\n",df[['customerReviewAverage', 'bestseller']].corr() )

Correlation between rating and bestseller:
                        customerReviewAverage  bestseller
customerReviewAverage               1.000000    0.080139
bestseller                          0.080139    1.000000

In [ ]:
import matplotlib.pyplot as plt
import plotly.express as go
import plotly.graph_objects as go