# Explotary Data Analysis for New Egg Products

In [35]:
# Load dataset and view basic structure
import pandas as pd
import numpy as np

df=pd.read_csv("filtered_products_newegg.csv")

## Check structure and dimensions

In [36]:
#shape
df.shape

(2605, 10)

In [37]:
# Check structure
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2605 entries, 0 to 2604
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   itemNumber             2605 non-null   object
 1   class                  2605 non-null   object
 2   name                   2603 non-null   object
 3   customerReviewAverage  2605 non-null   float64
 4   customerReviewCount    2605 non-null   int64
 5   customerTopRated       2605 non-null   bool
 6   modelNumber            2602 non-null   object
 7   salePrice              2605 non-null   float64
 8   manufacturer           2605 non-null   object
 9   isRefurbished          2605 non-null   bool
dtypes: bool(2), float64(2), int64(1), object(5)
memory usage: 168.0+ KB

In [38]:
# Missing values summary
df.isnull().sum()

itemNumber               0
class                    0
name                     2
customerReviewAverage    0
customerReviewCount      0
customerTopRated         0
modelNumber              3
salePrice                0
manufacturer             0
isRefurbished            0
dtype: int64

In [43]:
# Print the number of rows and columns
print(f"The number of rows= {df.shape[0]}")
print(f"The number of columns= {df.shape[1]}")

The number of rows= 2473
The number of columns= 10

## Columns and Data Types

In [44]:
#display the columns
df.columns

Index(['itemNumber', 'class', 'name', 'customerReviewAverage',
       'customerReviewCount', 'customerTopRated', 'modelNumber', 'salePrice',
       'manufacturer', 'isRefurbished'],
      dtype='object')

In [45]:
df.columns.to_list()

['itemNumber',
 'class',
 'name',
 'customerReviewAverage',
 'customerReviewCount',
 'customerTopRated',
 'modelNumber',
 'salePrice',
 'manufacturer',
 'isRefurbished']

In [46]:
# Data Types
df.dtypes

itemNumber                object
class                     object
name                      object
customerReviewAverage    float64
customerReviewCount        int64
customerTopRated            bool
modelNumber               object
salePrice                float64
manufacturer              object
isRefurbished               bool
dtype: object

## Clean Data

In [ ]:
#remove rows that are empty
df = df.dropna()

In [ ]:
# Drop duplicates if any
df.drop_duplicates(inplace=True)

In [ ]:
df.isnull().sum()

itemNumber               0
class                    0
name                     0
customerReviewAverage    0
customerReviewCount      0
customerTopRated         0
modelNumber              0
salePrice                0
manufacturer             0
isRefurbished            0
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2473 entries, 0 to 2603
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   itemNumber             2473 non-null   object
 1   class                  2473 non-null   object
 2   name                   2473 non-null   object
 3   customerReviewAverage  2473 non-null   float64
 4   customerReviewCount    2473 non-null   int64
 5   customerTopRated       2473 non-null   bool
 6   modelNumber            2473 non-null   object
 7   salePrice              2473 non-null   float64
 8   manufacturer           2473 non-null   object
 9   isRefurbished          2473 non-null   bool
dtypes: bool(2), float64(2), int64(1), object(5)
memory usage: 178.7+ KB

## Descriptive Statistics

In [47]:
# Summary statistics for numeric columns
df.describe()
df.describe(percentiles=[.1, .25, .5, .75, .9])

       customerReviewAverage  customerReviewCount    salePrice
count            2473.000000          2473.000000  2473.000000
mean                1.053255             7.947837   738.248124
std                 1.896560            48.753194   725.498526
min                 0.000000             0.000000    29.000000
10%                 0.000000             0.000000   179.990000
25%                 0.000000             0.000000   292.220000
50%                 0.000000             0.000000   499.990000
75%                 0.000000             0.000000   919.000000
90%                 4.700000             5.000000  1596.190000
max                 5.000000           892.000000  8100.000000

In [48]:
# Summary statistics for categorical columns
df.describe(include='object')

,itemNumber,class,name,modelNumber,manufacturer
count,2473,2473,2473,2473,2473
unique,2473,3,2442,2452,113
top,83-360-831,desktop,ABS Cyclone Aqua Gaming PC - Windows 11 - Inte...,FX608JHR-ES73,DELL
freq,1,959,2,4,399

In [49]:
# Univariate Analysis — Numerical
print('Review count Summary:\n ', df['customerReviewCount'].describe())
print('\nReview avg Score Summary:\n ', df['customerReviewAverage'].describe())
print('\n Sale Price Summary:\n ', df['salePrice'].describe())

# Univariate Analysis — Categorical
print('\nManufacturer Summary:\n ', df['manufacturer'].describe())
print('\nclass Summary:\n ', df['class'].describe())
print('\nModel number Summary:\n ', df['modelNumber'].describe())
print('\ncondition Summary:\n ', df['isRefurbished'].describe())
print('\nManufacturer num:\n ', df['manufacturer'].value_counts())
print('\nclass num:\n ', df['class'].value_counts())

Review count Summary:
  count    2473.000000
mean        7.947837
std        48.753194
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max       892.000000
Name: customerReviewCount, dtype: float64

Review avg Score Summary:
  count    2473.000000
mean        1.053255
std         1.896560
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max         5.000000
Name: customerReviewAverage, dtype: float64

 Sale Price Summary:
  count    2473.000000
mean      738.248124
std       725.498526
min        29.000000
25%       292.220000
50%       499.990000
75%       919.000000
max      8100.000000
Name: salePrice, dtype: float64

Manufacturer Summary:
  count     2473
unique     113
top       DELL
freq       399
Name: manufacturer, dtype: object

class Summary:
  count        2473
unique          3
top       desktop
freq          959
Name: class, dtype: object

Model number Summary:
  count              2473
unique             2452
top       FX608JHR-ES73
freq                  4
Name: modelNumber, dtype: object

condition Summary:
  count      2473
unique        2
top       False
freq       1329
Name: isRefurbished, dtype: object

Manufacturer num:
  manufacturer
DELL         399
HP           356
Apple        346
SAMSUNG      290
Lenovo       237
            ...
Fusion5        1
AQVIN          1
Auusda         1
N-one          1
ArsenalPC      1
Name: count, Length: 113, dtype: int64

class num:
  class
desktop    959
laptop     762
phone      752
Name: count, dtype: int64

## Summary Statistics Review

In [50]:

# Numerical summaries
print("Review Count")
print("Mean Review Count:", df['customerReviewCount'].mean())
print("Std of Review Count:",df['customerReviewCount'].std() )
print("Min & Max Review Count:",df['customerReviewCount'].min(), df['customerReviewCount'].max() )

print("\nReview Rating")
print("Mean Review Rating:", df['customerReviewAverage'].mean())
print("Std of Review Rating:",df['customerReviewAverage'].std() )
print("Min & Max Review Rating:",df['customerReviewAverage'].min(), df['customerReviewAverage'].max() )

print("\nSale Price")

print("Mean Sale Price:", df['salePrice'].mean())
print("Std of Sale Price:",df['salePrice'].std() )
print("Min & Max Sale Price:",df['salePrice'].min(), df['salePrice'].max() )

# Categorical summaries
print('\nManufacturer counts:\n ', df['manufacturer'].value_counts())
print('\nClass Counts:\n ', df['class'].value_counts())

Review Count
Mean Review Count: 7.947836635665184
Std of Review Count: 48.75319370057529
Min & Max Review Count: 0 892

Review Rating
Mean Review Rating: 1.0532551556813585
Std of Review Rating: 1.8965601095641056
Min & Max Review Rating: 0.0 5.0

Sale Price
Mean Sale Price: 738.2481237363525
Std of Sale Price: 725.4985257409029
Min & Max Sale Price: 29.0 8100.0

Manufacturer counts:
  manufacturer
DELL         399
HP           356
Apple        346
SAMSUNG      290
Lenovo       237
            ...
Fusion5        1
AQVIN          1
Auusda         1
N-one          1
ArsenalPC      1
Name: count, Length: 113, dtype: int64

Class Counts:
  class
desktop    959
laptop     762
phone      752
Name: count, dtype: int64

In [51]:
#unique value counts and mode detection
print("\nUnique value counts per column:")
print(df.nunique())

Unique value counts per column:
itemNumber               2473
class                       3
name                     2442
customerReviewAverage      27
customerReviewCount        81
customerTopRated            2
modelNumber              2452
salePrice                1294
manufacturer              113
isRefurbished               2
dtype: int64

## Exploring Relationships

In [52]:
# Group-based summaries

print("Mean Rating by Class:")
print(df.groupby('class')['customerReviewAverage'].mean())

print("\nMean Rating by Manufacturer:")
print(df.groupby('manufacturer')['customerReviewAverage'].mean())

print("\nMean Review Count by Class:")
print(df.groupby('class')['customerReviewCount'].mean())

print("\nMean Review Count by Manufacturer:")
print(df.groupby('manufacturer')['customerReviewCount'].mean())

print("\nMean Sale Price by Class:")
print(df.groupby('class')['salePrice'].mean())

print("\nMean Sale Price by Manufacturer:")
print(df.groupby('manufacturer')['salePrice'].mean())


# Correlation matrix

df.corr(numeric_only=True)

Mean Rating by Class:
class
desktop    1.936288
laptop     0.557218
phone      0.429787
Name: customerReviewAverage, dtype: float64

Mean Rating by Manufacturer:
manufacturer
8849          1.000000
ABS           2.920000
ACEMAGIC      3.216667
ALCPOK        4.900000
AOACE         4.700000
                ...
iBUYPOWER     3.254167
minisforum    4.200000
sluting       0.000000
suevery       2.500000
yeah magic    1.957143
Name: customerReviewAverage, Length: 113, dtype: float64

Mean Review Count by Class:
class
desktop    19.497393
laptop      0.968504
phone       0.291223
Name: customerReviewCount, dtype: float64

Mean Review Count by Manufacturer:
manufacturer
8849            0.500000
ABS            71.977778
ACEMAGIC        1.833333
ALCPOK        263.000000
AOACE         892.000000
                 ...
iBUYPOWER      17.416667
minisforum      9.250000
sluting         0.000000
suevery         0.500000
yeah magic      2.142857
Name: customerReviewCount, Length: 113, dtype: float64

Mean Sale Price by Class:
class
desktop    975.335026
laptop     745.185958
phone      428.869176
Name: salePrice, dtype: float64

Mean Sale Price by Manufacturer:
manufacturer
8849           449.495000
ABS           1576.109778
ACEMAGIC       305.958333
ALCPOK        1291.990000
AOACE          835.995000
                 ...
iBUYPOWER     1553.205000
minisforum     419.000000
sluting        339.000000
suevery        474.990000
yeah magic     808.427143
Name: salePrice, Length: 113, dtype: float64

,customerReviewAverage,customerReviewCount,customerTopRated,salePrice,isRefurbished
customerReviewAverage,1.000000,0.295798,0.351100,0.180925,-0.154840
customerReviewCount,0.295798,1.000000,0.469729,0.073285,-0.140283
customerTopRated,0.351100,0.469729,1.000000,0.097333,-0.158154
salePrice,0.180925,0.073285,0.097333,1.000000,-0.432343
isRefurbished,-0.154840,-0.140283,-0.158154,-0.432343,1.000000